import {
	Box,
	Circle,
	Flex,
	Heading,
	Text,
	useMediaQuery,
} from "@chakra-ui/react";
import React from "react";

export default function Whycarpalar() {
	const [notSmallerScreen] = useMediaQuery("(min-width:768px)");
	return (
		<Box>
			<Flex
				pt="10"
				bg="#fff"
				boxShadow="lg"
				minH="80vh"
				alignItems="center"
				flexDir="column"
				width="80vw"
				margin="auto"
				mt="-50"
				borderRadius="3"
			>
				<Heading
					as="h2"
					size={notSmallerScreen ? "2xl" : "1xl"}
					fontWeight="bold"
					textTransform="uppercase"
					textAlign="center"
				>
					Why Choose Carpalar?
				</Heading>
				<Flex
					flexWrap="wrap"
					justifyContent="space-evenly"
					px="10%"
					my="5%"
				>
					<Flex
						m="4"
						p="4"
						justifyContent="space-evenly"
						alignItems="center"
						minH="30vh"
						borderRadius="5"
						width="21%"
						flexDir="column"
						boxShadow="md"
					>
						<Text
							bg="#4C63FF"
							fontSize="4xl"
							fontWeight="black"
							height="60px"
							width="60px"
							textAlign="center"
							borderRadius="50%"
							color="#f2f2f2"
						>
							01
						</Text>

						<Text
							fontWeight="bold"
							textTransform="uppercase"
							fontSize="10"
							textAlign="center"
						>
							Flexible weekly payment plan
						</Text>
					</Flex>
					<Flex
						m="4"
						p="4"
						justifyContent="space-evenly"
						alignItems="center"
						minH="30vh"
						borderRadius="5"
						width="21%"
						flexDir="column"
						boxShadow="md"
					>
						<Text
							bg="#4C63FF"
							fontSize="4xl"
							fontWeight="black"
							height="60px"
							width="60px"
							textAlign="center"
							borderRadius="50%"
							color="#f2f2f2"
						>
							02
						</Text>

						<Text
							fontWeight="bold"
							textTransform="uppercase"
							fontSize="10"
							textAlign="center"
						>
							No Collateral, No worries. No hidden charges
						</Text>
					</Flex>
					<Flex
						m="4"
						p="4"
						justifyContent="space-evenly"
						alignItems="center"
						minH="30vh"
						borderRadius="5"
						width="21%"
						flexDir="column"
						boxShadow="md"
					>
						<Text
							bg="#4C63FF"
							fontSize="4xl"
							fontWeight="black"
							height="60px"
							width="60px"
							textAlign="center"
							borderRadius="50%"
							color="#f2f2f2"
						>
							03
						</Text>

						<Text
							fontWeight="bold"
							textTransform="uppercase"
							fontSize="10"
							textAlign="center"
						>
							Affordable & Low Deposit
						</Text>
					</Flex>
					<Flex
						m="4"
						p="4"
						justifyContent="space-evenly"
						alignItems="center"
						minH="30vh"
						borderRadius="5"
						width="21%"
						flexDir="column"
						boxShadow="md"
					>
						<Text
							bg="#4C63FF"
							fontSize="4xl"
							fontWeight="black"
							height="60px"
							width="60px"
							textAlign="center"
							borderRadius="50%"
							color="#f2f2f2"
						>
							04
						</Text>

						<Text
							fontWeight="bold"
							textTransform="uppercase"
							fontSize="10"
							textAlign="center"
						>
							No interest rate
						</Text>
					</Flex>
					<Flex
						m="4"
						p="4"
						justifyContent="space-evenly"
						alignItems="center"
						minH="30vh"
						borderRadius="5"
						width="21%"
						flexDir="column"
						boxShadow="md"
					>
						<Text
							bg="#4C63FF"
							fontSize="4xl"
							fontWeight="black"
							height="60px"
							width="60px"
							textAlign="center"
							borderRadius="50%"
							color="#f2f2f2"
						>
							05
						</Text>

						<Text
							fontWeight="bold"
							textTransform="uppercase"
							fontSize="10"
							textAlign="center"
						>
							Access to a Car
						</Text>
					</Flex>
					<Flex
						m="4"
						p="4"
						justifyContent="space-evenly"
						alignItems="center"
						minH="30vh"
						borderRadius="5"
						width="21%"
						flexDir="column"
						boxShadow="md"
					>
						<Text
							bg="#4C63FF"
							fontSize="4xl"
							fontWeight="black"
							height="60px"
							width="60px"
							textAlign="center"
							borderRadius="50%"
							color="#f2f2f2"
						>
							06
						</Text>

						<Text
							fontWeight="bold"
							textTransform="uppercase"
							fontSize="10"
							textAlign="center"
						>
							Compressive Insurance
						</Text>
					</Flex>
					<Flex
						m="4"
						p="4"
						justifyContent="space-evenly"
						alignItems="center"
						minH="30vh"
						borderRadius="5"
						width="21%"
						flexDir="column"
						boxShadow="md"
					>
						<Text
							bg="#4C63FF"
							fontSize="4xl"
							fontWeight="black"
							height="60px"
							width="60px"
							textAlign="center"
							borderRadius="50%"
							color="#f2f2f2"
						>
							07
						</Text>

						<Text
							fontWeight="bold"
							textTransform="uppercase"
							fontSize="10"
							textAlign="center"
						>
							24 Hours Support
						</Text>
					</Flex>
					<Flex
						m="4"
						p="4"
						justifyContent="space-evenly"
						alignItems="center"
						minH="30vh"
						borderRadius="5"
						width="21%"
						flexDir="column"
						boxShadow="md"
						overflow="hidden"
						position="relative"
					>
						<Circle
							bg="#4C63FF"
							position="absolute"
							right="0"
							left="0"
							bottom="-100"
							height="200px"
							width="200px"
						/>
						<Text
							zIndex="10"
							bg="#4C63FF"
							fontSize="4xl"
							fontWeight="black"
							height="60px"
							width="60px"
							textAlign="center"
							borderRadius="50%"
							color="#f2f2f2"
						>
							08
						</Text>
						<Text
							zIndex="10"
							fontWeight="bold"
							textTransform="uppercase"
							fontSize="10"
							textAlign="center"
						>
							Vehicle tracking
						</Text>
					</Flex>
				</Flex>
			</Flex>
		</Box>
	);
}
